inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - rabbit_messaging.gemspec
    - bin/console
    - environments/*.rb

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/HashConversion:
  Exclude:
    - spec/**/*

RSpec/VerifiedDoubleReference:
  EnforcedStyle: string
