name: Test

on: [push, pull_request]

jobs:
  full-check:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run on push event
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'umbrellio/rabbit_messaging'

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Create log dir
        run: mkdir -p log
      - name: Run Linter
        run: bundle exec rubocop
      - name: Run audit
        run: bundle exec rake bundle:audit
      - name: Run specs
        run: bundle exec rspec
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  specs:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    # We want to run on external PRs, but not on our own internal PRs as they'll be run on push event
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'umbrellio/rabbit_messaging'

    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6, 2.7]
        experimental: [false]
        include:
          - ruby: head
            experimental: true


    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Create log dir
        run: mkdir -p log
      - name: Run specs
        run: bundle exec rspec
